# Generated by Django 5.0.6 on 2024-06-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(choices=[('TOYOTA_COROLLA', 'Toyota Corolla'), ('HONDA_CIVIC', 'Honda Civic'), ('FORD_F150', 'Ford F-150'), ('CHEVROLET_SILVERADO', 'Chevrolet Silverado'), ('TESLA_MODEL_3', 'Tesla Model 3'), ('BMW_3_SERIES', 'BMW 3 Series'), ('AUDI_A4', 'Audi A4'), ('MERCEDES_BENZ_C_CLASS', 'Mercedes-Benz C-Class'), ('NISSAN_ALTIMA', 'Nissan Altima'), ('HYUNDAI_ELANTRA', 'Hyundai Elantra')], max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
