# Generated by Django 5.0.6 on 2024-06-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reservation_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at']},
        ),
    ]
